{{- if not .Values.disableIstio }}
{{- range .Values.services }}
{{- if .ports }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .name }}-vs
spec:
  hosts:
    - {{ .name }}
  http:
    - route:
    {{- $refName := .name -}}
    {{- range .versions }}
      - destination:
          host: {{ $refName }}
          subset: {{ .version }}
        weight: {{ .weight }}
    {{- end }}
---
{{- end }}
{{- end }}
{{- end }}